### ISSUE TITLE
More documentation needed

### ISSUE THREAD

**Issue by benmarwick** [mrecos/DistRegLMERR#1]
It would be good to see some more detail in the help pages, and a vignette. 

See my comments here: https://github.com/openjournals/joss-reviews/issues/722#issue-320042175

**Comment by mrecos** [comment]
All features are documented with titles, descriptions, parameters, notes, and examples.

**Comment by mrecos** [comment]
All features are documented with titles, descriptions, parameters, notes, and examples. Closing this issue
